<?php

declare(strict_types=1);

require_once __DIR__ . '/includes/database.php';
require_once __DIR__ . '/includes/functions.php';


// --------------------------------------------------
// CPAGrip Global Postback
// --------------------------------------------------

// CPAGrip sends POST requests.
// Direct browser visits should not be accepted.
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    header('Allow: POST');
    exit('Method Not Allowed');
}


// --------------------------------------------------
// Read CPAGrip POST data
// --------------------------------------------------

$offerId = isset($_POST['offer_id'])
    ? trim((string) $_POST['offer_id'])
    : '';

$trackingId = isset($_POST['tracking_id'])
    ? trim((string) $_POST['tracking_id'])
    : '';

$incomingPayout = isset($_POST['payout'])
    ? trim((string) $_POST['payout'])
    : '';


// --------------------------------------------------
// Basic validation
// --------------------------------------------------

if ($offerId === '' || $trackingId === '') {
    http_response_code(400);
    exit('Missing required parameters');
}


// Tracking IDs generated by PoketFlow are 32-character
// hexadecimal values.
if (!preg_match('/^[a-f0-9]{32}$/i', $trackingId)) {
    http_response_code(400);
    exit('Invalid tracking ID');
}


// Offer IDs should be simple numeric/string identifiers.
// Keep this validation flexible enough for future networks.
if (strlen($offerId) > 190) {
    http_response_code(400);
    exit('Invalid offer ID');
}


// payout is expected from CPAGrip, but we DO NOT trust it
// for wallet crediting. It is only validated/logged.
if ($incomingPayout !== '' && !is_numeric($incomingPayout)) {
    http_response_code(400);
    exit('Invalid payout');
}


// --------------------------------------------------
// Find CPAGrip network
// --------------------------------------------------

$networkStmt = $pdo->prepare("
    SELECT id, name, slug, status
    FROM networks
    WHERE slug = 'cpagrip'
    LIMIT 1
");

$networkStmt->execute();

$network = $networkStmt->fetch(PDO::FETCH_ASSOC);

if (!$network) {
    http_response_code(404);
    exit('CPAGrip network not found');
}

if ($network['status'] !== 'ACTIVE') {
    http_response_code(503);
    exit('CPAGrip network is inactive');
}

$networkId = (int) $network['id'];


// --------------------------------------------------
// Find the click and matching campaign
// --------------------------------------------------

$stmt = $pdo->prepare("
    SELECT
        cc.id AS click_id,
        cc.campaign_id,
        cc.worker_id,
        cc.tracking_id,
        cc.clicked_at,

        c.id AS campaign_db_id,
        c.network_id,
        c.external_offer_id,
        c.network_payout,
        c.reward_rate,
        c.worker_reward,
        c.platform_margin,
        c.status AS campaign_status,
        c.approval_status
    FROM campaign_clicks cc
    INNER JOIN campaigns c
        ON c.id = cc.campaign_id
    WHERE cc.tracking_id = :tracking_id
      AND c.network_id = :network_id
    LIMIT 1
");

$stmt->execute([
    ':tracking_id' => $trackingId,
    ':network_id' => $networkId,
]);

$click = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$click) {
    http_response_code(404);
    exit('Tracking ID not found');
}


// --------------------------------------------------
// Verify offer ID
// --------------------------------------------------

if ((string) $click['external_offer_id'] !== $offerId) {
    http_response_code(400);
    exit('Offer ID does not match tracking ID');
}


// --------------------------------------------------
// Verify campaign is still valid
// --------------------------------------------------

if ($click['campaign_status'] !== 'ACTIVE') {
    http_response_code(400);
    exit('Campaign is not active');
}

if ($click['approval_status'] !== 'APPROVED') {
    http_response_code(400);
    exit('Campaign is not approved');
}


// --------------------------------------------------
// Determine authoritative payout
// --------------------------------------------------

// IMPORTANT:
// We do not trust $_POST['payout'] for wallet crediting.
//
// The campaign payout stored in PoketFlow is authoritative.
// This prevents somebody from manually POSTing a huge payout
// to the public endpoint.

$networkPayout = (float) $click['network_payout'];

if ($networkPayout <= 0) {
    http_response_code(400);
    exit('Campaign payout is invalid');
}


// --------------------------------------------------
// Determine reward rate
// --------------------------------------------------

$rewardRate = isset($click['reward_rate'])
    ? (float) $click['reward_rate']
    : 60.00;

if ($rewardRate <= 0 || $rewardRate > 100) {
    $rewardRate = 60.00;
}


// --------------------------------------------------
// Calculate worker reward and platform margin
// --------------------------------------------------

$workerReward = round(
    $networkPayout * ($rewardRate / 100),
    2
);

$platformMargin = round(
    $networkPayout - $workerReward,
    2
);

$workerId = (int) $click['worker_id'];
$campaignId = (int) $click['campaign_id'];


// --------------------------------------------------
// Create deterministic transaction ID
// --------------------------------------------------

// This allows us to identify the same CPAGrip conversion
// if CPAGrip sends the postback more than once.

$externalTransactionId =
    'cpagrip:' . $offerId . ':' . $trackingId;


// --------------------------------------------------
// Process conversion atomically
// --------------------------------------------------

try {

    $pdo->beginTransaction();


    // ----------------------------------------------
    // Check for duplicate conversion
    // ----------------------------------------------

    $duplicateStmt = $pdo->prepare("
        SELECT id
        FROM conversions
        WHERE network_id = :network_id
          AND external_transaction_id = :external_transaction_id
        LIMIT 1
        FOR UPDATE
    ");

    $duplicateStmt->execute([
        ':network_id' => $networkId,
        ':external_transaction_id' => $externalTransactionId,
    ]);

    $existingConversion = $duplicateStmt->fetch(PDO::FETCH_ASSOC);


    if ($existingConversion) {

        $pdo->commit();

        // CPAGrip may retry a postback.
        // Returning OK prevents unnecessary retries.
        http_response_code(200);
        exit('OK');
    }


    // ----------------------------------------------
    // Get current worker balance
    // ----------------------------------------------

    $balanceBefore = getUserBalance(
        $pdo,
        $workerId
    );

    $balanceAfter = round(
        $balanceBefore + $workerReward,
        2
    );


    // ----------------------------------------------
    // Insert conversion
    // ----------------------------------------------

    $conversionStmt = $pdo->prepare("
        INSERT INTO conversions (
            campaign_id,
            worker_id,
            network_id,
            external_transaction_id,
            network_payout,
            reward_rate,
            worker_reward,
            platform_margin,
            status,
            converted_at
        )
        VALUES (
            :campaign_id,
            :worker_id,
            :network_id,
            :external_transaction_id,
            :network_payout,
            :reward_rate,
            :worker_reward,
            :platform_margin,
            'APPROVED',
            NOW()
        )
    ");

    $conversionStmt->execute([
        ':campaign_id' => $campaignId,
        ':worker_id' => $workerId,
        ':network_id' => $networkId,
        ':external_transaction_id' => $externalTransactionId,
        ':network_payout' => $networkPayout,
        ':reward_rate' => $rewardRate,
        ':worker_reward' => $workerReward,
        ':platform_margin' => $platformMargin,
    ]);

    $conversionId = (int) $pdo->lastInsertId();


    // ----------------------------------------------
    // Add reward to wallet ledger
    // ----------------------------------------------

    $walletStmt = $pdo->prepare("
        INSERT INTO wallet_transactions (
            user_id,
            type,
            reference_type,
            reference_id,
            amount,
            currency,
            balance_before,
            balance_after,
            status,
            description
        )
        VALUES (
            :user_id,
            'OFFER_REWARD',
            'CONVERSION',
            :reference_id,
            :amount,
            'USD',
            :balance_before,
            :balance_after,
            'COMPLETED',
            :description
        )
    ");

    $walletStmt->execute([
        ':user_id' => $workerId,
        ':reference_id' => $conversionId,
        ':amount' => $workerReward,
        ':balance_before' => $balanceBefore,
        ':balance_after' => $balanceAfter,
        ':description' => 'CPAGrip offer reward',
    ]);


    // ----------------------------------------------
    // Commit everything
    // ----------------------------------------------

    $pdo->commit();


    // ----------------------------------------------
    // Success
    // ----------------------------------------------

    http_response_code(200);
    exit('OK');


} catch (Throwable $e) {

    if ($pdo->inTransaction()) {
        $pdo->rollBack();
    }

    error_log(
        'PoketFlow CPAGrip postback error: '
        . $e->getMessage()
    );

    http_response_code(500);
    exit('Server Error');
}
