<?php

declare(strict_types=1);

require_once __DIR__ . '/includes/database.php';
require_once __DIR__ . '/includes/functions.php';


// --------------------------------------------------
// Only accept POST requests
// --------------------------------------------------

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo 'Method Not Allowed';
    exit;
}


// --------------------------------------------------
// Load private CPAGrip configuration
// --------------------------------------------------

$cpagripConfigPath = '/home/u541027683/private/poketflow-cpagrip.php';

if (!is_file($cpagripConfigPath)) {
    http_response_code(500);
    echo 'Configuration Error';
    exit;
}

$cpagripConfig = require $cpagripConfigPath;

$postbackPassword = (string) (
    $cpagripConfig['postback_password'] ?? ''
);


// --------------------------------------------------
// Verify CPAGrip password
// --------------------------------------------------

$password = isset($_POST['password'])
    ? (string) $_POST['password']
    : '';

if (
    $postbackPassword === ''
    || $password === ''
    || !hash_equals($postbackPassword, $password)
) {
    http_response_code(403);
    echo 'Access Denied';
    exit;
}


// --------------------------------------------------
// Read CPAGrip variables
// --------------------------------------------------

$offerId = isset($_POST['offer_id'])
    ? trim((string) $_POST['offer_id'])
    : '';

$trackingId = isset($_POST['tracking_id'])
    ? trim((string) $_POST['tracking_id'])
    : '';

$payoutRaw = isset($_POST['payout'])
    ? trim((string) $_POST['payout'])
    : '';


// --------------------------------------------------
// Validate required variables
// --------------------------------------------------

if ($offerId === '' || $trackingId === '' || $payoutRaw === '') {
    http_response_code(400);
    echo 'Missing Parameters';
    exit;
}


// --------------------------------------------------
// Validate payout
// --------------------------------------------------

if (!is_numeric($payoutRaw)) {
    http_response_code(400);
    echo 'Invalid Payout';
    exit;
}

$networkPayout = round((float) $payoutRaw, 2);

if ($networkPayout <= 0) {
    http_response_code(400);
    echo 'Invalid Payout';
    exit;
}


// --------------------------------------------------
// Find CPAGrip network
// --------------------------------------------------

$stmt = $pdo->prepare(
    "SELECT id
     FROM networks
     WHERE slug = :slug
       AND status = 'ACTIVE'
     LIMIT 1"
);

$stmt->execute([
    ':slug' => 'cpagrip',
]);

$network = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$network) {
    http_response_code(500);
    echo 'Network Not Available';
    exit;
}

$networkId = (int) $network['id'];


// --------------------------------------------------
// Find the original campaign click
//
// tracking_id was generated by PoketFlow when the
// worker clicked the offer.
// --------------------------------------------------

$stmt = $pdo->prepare(
    "SELECT
        cc.id AS click_id,
        cc.campaign_id,
        cc.worker_id,
        cc.tracking_id,

        c.network_id,
        c.external_offer_id,
        c.title,
        c.reward_rate,
        c.status,
        c.approval_status

     FROM campaign_clicks cc

     INNER JOIN campaigns c
        ON c.id = cc.campaign_id

     WHERE cc.tracking_id = :tracking_id
       AND c.network_id = :network_id
     LIMIT 1"
);

$stmt->execute([
    ':tracking_id' => $trackingId,
    ':network_id' => $networkId,
]);

$click = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$click) {
    http_response_code(404);
    echo 'Tracking ID Not Found';
    exit;
}


// --------------------------------------------------
// Verify that CPAGrip sent the expected offer ID
// --------------------------------------------------

if ((string) $click['external_offer_id'] !== $offerId) {
    http_response_code(400);
    echo 'Offer Mismatch';
    exit;
}


$campaignId = (int) $click['campaign_id'];
$workerId = (int) $click['worker_id'];


// --------------------------------------------------
// Determine reward rate
//
// Campaign-specific reward rate takes priority.
// --------------------------------------------------

$rewardRate = $click['reward_rate'];

if ($rewardRate === null || $rewardRate === '') {
    $rewardRate = isset($cpagripConfig['reward_rate'])
        ? (float) $cpagripConfig['reward_rate']
        : 0.60;
} else {
    $rewardRate = (float) $rewardRate / 100;
}

if ($rewardRate < 0) {
    $rewardRate = 0;
}

if ($rewardRate > 1) {
    $rewardRate = 1;
}


// --------------------------------------------------
// Calculate worker reward
// --------------------------------------------------

$workerReward = round(
    $networkPayout * $rewardRate,
    2
);

$platformMargin = round(
    $networkPayout - $workerReward,
    2
);


// --------------------------------------------------
// Create a deterministic transaction reference
//
// CPAGrip gives us offer_id + tracking_id but does
// not provide a separate transaction ID in the
// Global Postback variables supplied to us.
//
// Because every PoketFlow click has a unique
// tracking_id, this combination identifies this
// conversion safely.
// --------------------------------------------------

$externalTransactionId = 'cpagrip:'
    . $offerId
    . ':'
    . $trackingId;


// --------------------------------------------------
// Begin atomic conversion + wallet transaction
// --------------------------------------------------

try {

    $pdo->beginTransaction();


    // --------------------------------------------------
    // Check whether this conversion was already processed
    // --------------------------------------------------

    $stmt = $pdo->prepare(
        "SELECT id, status
         FROM conversions
         WHERE network_id = :network_id
           AND external_transaction_id = :external_transaction_id
         LIMIT 1
         FOR UPDATE"
    );

    $stmt->execute([
        ':network_id' => $networkId,
        ':external_transaction_id' => $externalTransactionId,
    ]);

    $existingConversion = $stmt->fetch(PDO::FETCH_ASSOC);


    if ($existingConversion) {

        $pdo->commit();

        // CPAGrip may retry a postback.
        // Returning success prevents unnecessary
        // repeated processing.
        http_response_code(200);
        echo 'OK';
        exit;
    }


    // --------------------------------------------------
    // Get current worker balance
    // --------------------------------------------------

    $balanceBefore = getUserBalance(
        $pdo,
        $workerId
    );

    $balanceAfter = round(
        $balanceBefore + $workerReward,
        2
    );


    // --------------------------------------------------
    // Create conversion
    // --------------------------------------------------

    $stmt = $pdo->prepare(
        "INSERT INTO conversions (
            campaign_id,
            worker_id,
            network_id,
            external_transaction_id,
            network_payout,
            reward_rate,
            worker_reward,
            platform_margin,
            status,
            converted_at
        )
        VALUES (
            :campaign_id,
            :worker_id,
            :network_id,
            :external_transaction_id,
            :network_payout,
            :reward_rate,
            :worker_reward,
            :platform_margin,
            'APPROVED',
            NOW()
        )"
    );

    $stmt->execute([
        ':campaign_id' => $campaignId,
        ':worker_id' => $workerId,
        ':network_id' => $networkId,
        ':external_transaction_id' => $externalTransactionId,
        ':network_payout' => $networkPayout,
        ':reward_rate' => round($rewardRate * 100, 2),
        ':worker_reward' => $workerReward,
        ':platform_margin' => $platformMargin,
    ]);

    $conversionId = (int) $pdo->lastInsertId();


    // --------------------------------------------------
    // Create wallet transaction
    // --------------------------------------------------

    $stmt = $pdo->prepare(
        "INSERT INTO wallet_transactions (
            user_id,
            type,
            reference_type,
            reference_id,
            amount,
            currency,
            balance_before,
            balance_after,
            status,
            description
        )
        VALUES (
            :user_id,
            'OFFER_REWARD',
            'CONVERSION',
            :reference_id,
            :amount,
            'USD',
            :balance_before,
            :balance_after,
            'COMPLETED',
            :description
        )"
    );

    $stmt->execute([
        ':user_id' => $workerId,
        ':reference_id' => $conversionId,
        ':amount' => $workerReward,
        ':balance_before' => $balanceBefore,
        ':balance_after' => $balanceAfter,
        ':description' => 'CPAGrip offer reward: ' . $offerId,
    ]);


    // --------------------------------------------------
    // Commit everything
    // --------------------------------------------------

    $pdo->commit();


    // --------------------------------------------------
    // Success
    // --------------------------------------------------

    http_response_code(200);
    echo 'OK';
    exit;


} catch (Throwable $e) {

    if ($pdo->inTransaction()) {
        $pdo->rollBack();
    }

    error_log(
        'PoketFlow CPAGrip Postback Error: '
        . $e->getMessage()
    );

    http_response_code(500);
    echo 'Server Error';
    exit;
}
